# -*- coding: utf-8 -*-
"""
Created on 2023-05-28 13:27:56
---------
@summary:
---------
@author: FQCj
"""

from feapder import Item


class XiachufangitemItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i xiachufangitem
    """

    __table_name__ = "xiachufangitem"

    def __init__(self, *args, **kwargs):
        # self.id = None
        super().__init__(**kwargs)
        self.firstLevelLabel = None
        self.secondaryLabel = None
        self.item_url = None
        self.title = None
        self.htmlText = None
