# -*- coding: utf-8 -*-
"""
Created on 2023-05-28 11:49:57
---------
@summary:
---------
@author: FQCj
"""

from feapder import Item


class XiachufanglabelItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i xiachufanglabel
    """

    __table_name__ = "xiachufanglabel"

    def __init__(self, *args, **kwargs):
        # self.id = None
        super().__init__(**kwargs)
        self.firstLevelLabel = None
        self.secondaryLabel = None
        self.dir_url = None
