# -*- coding: utf-8 -*-
"""
Created on 2023-05-28 21:22:53
---------
@summary:
---------
@author: FQCj
"""

from feapder import Item


class MeishitxiaItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i meishitxia
    """

    __table_name__ = "meishitxia"

    def __init__(self, *args, **kwargs):
        # self.id = None
        super().__init__(**kwargs)
        self.firstLevelLabel = None
        self.secondaryLabel = None
        self.pageAddress = None
        self.title = None
        self.details = None
        self.img_href = None
        self.item_href = None
        self.html = None
