# Generated by Django 3.1.7 on 2022-11-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20221111_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.CharField(max_length=64, verbose_name='站点样式'),
        ),
    ]
